[package]
name = "scoa"
version = "0.1.1"
edition = "2024"
description = "Simpler Cloud-optimized Archive"

[dependencies]
byteorder = "1.5.0"
flate2 = "1.1.1"
itertools = "0.14.0"
leb128 = "0.2.5"
thiserror = "2.0.12"
